export const SET_PRODUCT_DATA = 'SET_PRODUCT_DATA';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR';
